[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://api.smallrobot.co/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
